### ISSUE TITLE
Passing by value is expensive.

### ISSUE THREAD

**Issue by summerinsects** [fnz/EasyJNI#2]
template <typename T, typename... Ts>
std::string getJNISignature(T x, Ts... xs)

template <>
std::string getJNISignature(std::string) {
    return "Ljava/lang/String;";
}

jstring convert(cocos2d::JniMethodInfo& t, std::string x) {
    return t.env->NewStringUTF(x.c_str());
}

Passing by value is expensive. As a rule passing by const reference is better, if you don't need to modify you function argument locally.

**Comment by fnz** [comment]
Thanks, this part will be refactored completely
